#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Dec 12 10:27:40 CST 2023
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 73c4b297a91b4849a59d673faacfec88 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_redundant_adder_tree_behav xil_defaultlib.tb_redundant_adder_tree -log elaborate.log"
xelab -wto 73c4b297a91b4849a59d673faacfec88 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_redundant_adder_tree_behav xil_defaultlib.tb_redundant_adder_tree -log elaborate.log

